@baseUrl = https://localhost:5236
@contentType = application/json

#  Submit plaintext transaction
POST {{baseUrl}}/transactions
Content-Type: {{contentType}}

{
  "emvHex": "9F02060000000001809F150212349F010312349C0100",
  "mode": "plaintext"
}

#  Submit encrypted transaction
POST {{baseUrl}}/transactions
Content-Type: {{contentType}}

{
  "emvHex": "ENCRYPTED_BASE64_PAYLOAD",
  "mode": "encrypted",
  "signature": "HMAC_SIGNATURE_BASE64"
}


#  Retrieve transaction
GET {{baseUrl}}/transactions/{{lastTransactionId}}
Accept: application/json
